version: '3'

services:
  bot:
    image: ${IMAGE_REF}
    container_name: readtipbot
    restart: always
    environment:
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
      - READ_TIP_BOT_STORAGE=/usr/src/storage